# Generated by Django 5.0.7 on 2024-07-10 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCISession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('date_recorded', models.DateTimeField()),
                ('subject_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BCIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('channel_1', models.FloatField()),
                ('channel_2', models.FloatField()),
                ('channel_3', models.FloatField()),
                ('channel_4', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='bci_data.bcisession')),
            ],
        ),
    ]
