version: '3.8'

services:
  web:
    build: .
    command: python bci_platform/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bci_dataflow
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bci_dataflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  data_generator:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bci_dataflow
    command: >
      sh -c "python bci_platform/manage.py migrate &&
             python scripts/generate_test_data.py &&
             python scripts/analyze_test_data.py"

volumes:
  postgres_data:
